# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from demo_page import DemoPage

class TestDemo:
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.page = DemoPage(self.driver)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demo(self):
    self.driver.get("https://tdd-detroid.onrender.com/")
    self.driver.set_window_size(970, 555)

    self.page.wait_page_load()   

    self.page.add_student(student="douglas")
    assert(
      "INFO Added student id: 1, Name: douglas" 
      in self.driver.find_element(By.CSS_SELECTOR, ".py-p").text
    )  

    self.page.add_course()
    assert(
      "INFO Added student id: 1, Name: douglas"
      in self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(2)").text
    ) 

    self.page.add_student_to_course()
    assert(
      "INFO Added student id: 1, Name: douglas"
      in self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(3)").text 
    ) 

    self.page.subscribe_discipline_to_course()
    assert(
      "FAIL Necessários 3 cursos para se criar a primeira matéria"
      in self.page.get_first_log()
    ) 

    self.page.add_course_tmp(course="port")

    self.page.add_course_tmp(course="geo")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn").click()
    assert(
      "INFO Added discipline id: 1, Name: mat, Course: 1"
      in self.page.get_first_log()
    ) 

   
    self.page.add_discipline_tmp(discipline="mat2")

    self.page.add_discipline_tmp(discipline="mat3")

    self.page.subscribe_student_to_discipline()
    self.driver.find_element(By.CSS_SELECTOR, ".py-p:nth-child(1)").click()
    assert(
      "WARN Aluno deve se inscrever em 3 materias no minimo"
      in self.page.get_first_log()
    ) 

    self.page.subscribe_to_discipline_tmp(discipline_id="2")
    self.page.subscribe_to_discipline_tmp(discipline_id="3")
    self.page.add_discipline_tmp(discipline="mat4")
    self.page.subscribe_to_discipline_tmp(discipline_id="4")
    self.driver.close()

  
  
